version: "3"
services:
  web:
    build: .
    ports:
      - "8080:8080"
    environment:
      - FLASK_APP=app.py
      - FLASK_DEBUG=1
    volumes:
      - .:/app
    command: flask run --host=0.0.0.0
